### ISSUE TITLE
[1.18.2] NoClassDefFoundError plugin

### ISSUE THREAD

**Issue by XionioXMaster** [Luohuayu/CatServer#410]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 
Build version(Get from /version command): CatServer-1.18.2-2812015-server
Mods/Plugins: MobHeads v1.2.1 - https://www.spigotmc.org/resources/mob-head-drops-behead.98077/
[Архив ZIP - WinRAR.zip](https://github.com/Luohuayu/CatServer/files/8570443/ZIP.-.WinRAR.zip)

**Describe the bug**
[(If there is an error, please attach the pastebin link)](https://paste.loliidc.cn/?d92b5b2e7009eadf#F4wBdrKZw8pY4PcXULPu7jhufzuYnFik8qhwNPGAWUL7)

As far as I understood, it is impossible to find the required class. But the plugin works on Patina 1.18.2

**Comment by Kotori0629** [comment]
Thank you very much for your high attention to CatServer1.18.2, we're still working on it, so stay tuned for me to send a test invite to your Discord
